name: Scrape Huskers Schedule

on:
  workflow_dispatch: {}
  schedule:
    - cron: "24 11 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers (Chromium)
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper (Playwright)
        run: python scrape_playwright.py
      
      - name: Build stadium manifest
        run: python build_stadium_manifest.py

      - name: Commit JSON and manifest if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/current.json data/stadium_manifest.json STADIUMS.md
            git commit -m "update: schedule + stadium manifest"
            git push
          else
            echo "No changes to commit."
          fi
