name: Scrape Huskers Schedule

on:
  workflow_dispatch: {}
  schedule:
    - cron: "24 11 * * *"  # daily at 11:24 UTC

permissions:
  contents: write  # allow the workflow to push the JSON back to the repo

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      - name: Commit JSON if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/huskers_schedule.json
            git commit -m "chore: update schedule JSON"
            git push
          else
            echo "No changes to commit."
          fi
